### ISSUE TITLE
Error: No metadata files found for isopack 

### ISSUE THREAD

**Issue by TheLuckiest** [fourseven/meteor-scss#157]
Hi there, I've tried running meteor on two apps so far: PlexRequests and The Meteor Chef Base and I've gotten this error every time, regardless of administrator access:

Error: No metadata files found for isopack at: /C/Users/Andy/AppData/Local/.mete
or/packages/fourseven_scss/3.4.1
at Object.Future.wait (C:\Users\Andy\AppData\Local.meteor\packages\meteor-t
ool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fibers\future.js:398
:15)
at C:\tools\utils\buildmessage.js:576:31
at Array.forEach (native)
at Function..each..forEach (C:\Users\Andy\AppData\Local.meteor\packages\m
eteor-tool\1.1.10\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\un
derscore.js:79:11)
at C:\tools\utils\buildmessage.js:574:9
at C:\tools\utils\buildmessage.js:356:18
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
at C:\tools\utils\buildmessage.js:349:34
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
at C:\tools\utils\buildmessage.js:347:23
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
at enterJob (C:\tools\utils\buildmessage.js:321:26)
at Object.forkJoin (C:\tools\utils\buildmessage.js:552:3)
at [object Object]._.extend.downloadPackagesMissingFromMap (C:\tools\packagi
ng\tropohouse.js:584:18)
at C:\tools\project-context.js:702:25
at C:\tools\utils\buildmessage.js:356:18
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
at C:\tools\utils\buildmessage.js:349:34
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
at C:\tools\utils\buildmessage.js:347:23
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
at C:\tools\project-context.js:701:20
at C:\tools\packaging\catalog\catalog.js:100:5
at C:\tools\utils\buildmessage.js:268:13
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
at C:\tools\utils\buildmessage.js:261:29
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
at C:\tools\utils\buildmessage.js:259:18
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
at C:\tools\utils\buildmessage.js:250:23
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
at Object.capture (C:\tools\utils\buildmessage.js:249:19)
at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalo
g\catalog.js:99:31)
at ProjectContext._.extend._downloadMissingPackages (C:\tools\project-contex
t.js:700:13)
at C:\tools\project-context.js:257:35
at C:\tools\utils\buildmessage.js:356:18
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
at C:\tools\utils\buildmessage.js:349:34
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
at C:\tools\utils\buildmessage.js:347:23
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
at Object.enterJob (C:\tools\utils\buildmessage.js:321:26)
at ProjectContext._.extend._completeStagesThrough (C:\tools\project-context.
js:247:18)
at ProjectContext._.extend.saveChangedMetadata (C:\tools\project-context.js:
235:10)
at ProjectContext._.extend.prepareProjectForBuild (C:\tools\project-context.
js:240:10)
at C:\tools\runners\run-app.js:517:29
at C:\tools\utils\buildmessage.js:268:13
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
at C:\tools\utils\buildmessage.js:261:29
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
at C:\tools\utils\buildmessage.js:259:18
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
at C:\tools\utils\buildmessage.js:250:23
at [object Object]._.extend.withValue (C:\tools\utils\fiber-helpers.js:114:1
4)
at Object.capture (C:\tools\utils\buildmessage.js:249:19)
at bundleApp (C:\tools\runners\run-app.js:516:31)
at [object Object]._.extend._runOnce (C:\tools\runners\run-app.js:594:35)
at [object Object].

I'm on Windows 10. If you need any additional information or want me to try anything, please let me know!

Thank you very much!

**Comment by TheLuckiest** [comment]
Nevermind, my mistake! I was able to get it running with a fresh install.

Thanks!

**Comment by malinovsky239** [comment]
@TheLuckiest Could you please specify what did cause that error and how have you got rid of it? Did just re-installing help (for me, it doesn't)?

**Comment by tamltn93** [comment]
@TheLuckiest  Hi Andy, Please help me. I have a sane issue. How do you fix it ?

**Comment by sebakerckhof** [comment]
If anyone could create a reproducable project/repo i could look into it

**Comment by tamltn93** [comment]
@sebakerckhof  Hi, I'm following this repo https://github.com/pors/reactionic-kitchensink

**Comment by sebakerckhof** [comment]
This seems to me like for some reason the package cache is corrupted. If you're on windows, try removing the following directory: `%LOCALAPPDATA%\.meteor\packages\fourseven_scss`

**Comment by tamltn93** [comment]
@sebakerckhof It not work with me

**Comment by nfabacus** [comment]
I have got the same problem with one of my window machine.  I reinstalled Meteor, but did not work.  Interestingly, the same app works on another window machine.

**Comment by sebakerckhof** [comment]
@nfabacus I'm not sure if reinstalling meteor cleans the package cache. Can you try removing tge cached package manually as decribed above?

**Comment by nfabacus** [comment]
@sebakerckhof Sorry how can I access the cached package?  You mean removing it from the Meteor package file?

**Comment by sebakerckhof** [comment]
@nfabacus Meteor downloads every package you use in the meteor installation folder.
For windows this is here: %LOCALAPPDATA%\.meteor\packages\fourseven_scss
for linux/mac this is usually ~/.meteor/packages/fourseven_scss

Delete all versions listed in those directories.
