### ISSUE TITLE
Error: No metadata files found for isopack

### ISSUE THREAD

**Issue by Cleanshooter** [fourseven/meteor-scss#179]
Meteor Version 1.3.2.4 
Windows 10
Trying to add package:

```
C:\Users\Moto\Documents\Projects\RMA Generic\Submit RMA node app\submitRmaWeb>meteor add fourseven:scss

C:\Users\Moto\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:116
      throw error;
            ^
Error: No metadata files found for isopack at: /C/Users/Moto/AppData/Local/.meteor/packages/fourseven_scss/3.4.3
    at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:900:13)
    at C:\tools\packaging\tropohouse.js:514:19
    at Array.forEach (native)
    at Function._.each._.forEach (C:\Users\Moto\AppData\Local\.meteor\packages\meteor-tool\1.3.2_4\mt-os.windows.x86_32\dev_bundle\lib\node_modules\underscore\underscore.js:79:11)
    at C:\tools\packaging\tropohouse.js:513:11
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at Object.download (C:\tools\packaging\tropohouse.js:448:20)
    at C:\tools\packaging\tropohouse.js:593:22
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at [object Object].downloadPackagesMissingFromMap (C:\tools\packaging\tropohouse.js:590:20)
    at C:\tools\project-context.js:725:25
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at C:\tools\project-context.js:724:20
    at C:\tools\packaging\catalog\catalog.js:100:5
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Object.catalog.runAndRetryWithRefreshIfHelpful (C:\tools\packaging\catalog\catalog.js:99:31)
    at ProjectContext._.extend._downloadMissingPackages (C:\tools\project-context.js:723:13)
    at C:\tools\project-context.js:278:9
    at C:\tools\utils\buildmessage.js:359:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:352:34
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:350:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
    at ProjectContext._completeStagesThrough (C:\tools\project-context.js:268:18)
    at C:\tools\project-context.js:260:12
    at Function.run (C:\tools\tool-env\profile.js:489:12)
    at ProjectContext.prepareProjectForBuild (C:\tools\project-context.js:259:13)
    at C:\tools\cli\commands-packages.js:2032:20
    at C:\tools\utils\buildmessage.js:271:13
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:264:29
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:262:18
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at C:\tools\utils\buildmessage.js:253:23
    at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
    at Object.capture (C:\tools\utils\buildmessage.js:252:19)
    at Command.main.registerCommand.name [as func] (C:\tools\cli\commands-packages.js:2031:27)
    at C:\tools\cli\main.js:1402:23
```
The following works:
`meteor add fourseven:scss@=3.4.2`

**Comment by sebakerckhof** [comment]
This is a problem with meteor packages sometimes being corrupt. You need to either clean your package cache or try to use the new 3.8.0 version.

**Comment by danyltsiv** [comment]
How can I clean my package cache??

**Comment by legna0616** [comment]
hi @sebakerckhof im using window 7 
meteor ver 1.4 , ih having the same problem

Error: No metadata files found for isopack at: /C/Users/WINTELOGIC/AppData/Local
/.meteor/packages/coffeescript/1.0.17
   at Isopack._loadUnibuildsFromPath (C:\tools\isobuild\isopack.js:900:13)
   at C:\tools\packaging\tropohouse.js:521:21
   at Array.forEach (native)
   at Function._.each._.forEach (C:\Users\WINTELOGIC\AppData\Local\.meteor\pack
ages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\unders
core\underscore.js:79:11)
   at C:\tools\packaging\tropohouse.js:520:13
   at C:\tools\utils\buildmessage.js:359:18
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:352:34
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:350:23
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
   at C:\tools\packaging\tropohouse.js:515:22
   at C:\tools\utils\buildmessage.js:359:18
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:352:34
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at C:\tools\utils\buildmessage.js:350:23
   at [object Object].withValue (C:\tools\utils\fiber-helpers.js:89:14)
   at Object.enterJob (C:\tools\utils\buildmessage.js:324:26)
   at Object.download (C:\tools\packaging\tropohouse.js:427:20)
   at C:\tools\packaging\tropohouse.js:613:18
   at C:\tools\utils\buildmessage.js:572:21
   at C:\Users\WINTELOGIC\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt
-os.windows.x86_32\dev_bundle\lib\node_modules\meteor-promise\fiber_pool.js:32:3

**Comment by sebakerckhof** [comment]
@legna0616 That error comes from from the coffeescript plugin...
Anyway this is an issue with Meteor/NPM.
