### ISSUE TITLE
[METEOR@1.4-beta.5] Node Sass does not find binding for env: OS X 64-bit with Node.js 4.x

### ISSUE THREAD

**Issue by stuhlmueller** [fourseven/meteor-scss#190]
Create a new project as follows to reproduce the error:

~~~~
$ rm -rf ~/.meteor/packages/fourseven_scss/
$ nvm use v4.4.5
$ meteor create test-scss
$ cd test-scss
$ meteor update --release 1.4-beta.5

    Changes to your project's package version selections from updating the release:
    
    autoupdate             upgraded from 1.2.10 to 1.2.11-beta.5
    babel-compiler         upgraded from 6.8.3 to 6.9.0-beta.5
    ...
    templating             upgraded from 1.1.12_1 to 1.1.13-beta.5
    webapp                 upgraded from 1.2.9_1 to 1.2.10-beta.5
    
    test-scss: updated to Meteor 1.4-beta.5.

$ meteor add fourseven:scss

    Changes to your project's package version selections:
    
    fourseven:scss  added, version 3.8.0_1
    
    fourseven:scss: Style with attitude. Sass and SCSS support for Meteor.js.

$ meteor

    [[[[[ ~/test-scss ]]]]]
    
    => Started proxy.
    => Started MongoDB.
    => Errors prevented startup:
    
       While loading plugin `compileScssBatch` from package `fourseven:scss`:
       ~/.meteor/packages/fourseven_scss/.3.8.0_1.n64xlo++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/node-sass/lib/index.js:15:11:
       Missing binding
       ~/.meteor/packages/fourseven_scss/.3.8.0_1.n64xlo++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/node-sass/vendor/darwin-x64-46/binding.node
       Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 4.x
    
       Found bindings for the following environments:
       - Unknown environment (.meteor-portable)
       - OS X 64-bit with Node 0.10.x
    
       This usually happens because your environment has changed since running `npm install`.
       Run `npm rebuild node-sass` to build the binding for your current environment.
       at Object.<anonymous>
       (~/.meteor/packages/fourseven_scss/.3.8.0_1.n64xlo++os.osx.x86_64+web.browser+web.cordova/plugin.compileScssBatch.os.osx.x86_64/npm/node_modules/meteor/compileScssBatch/node_modules/node-sass/lib/index.js:15:11)
       at Module._compile (module.js:409:26)
       at Object.Module._extensions..js (module.js:416:10)
       at Module.load (module.js:343:32)
       ...
~~~~

Any ideas on how to fix this?

**Comment by sebakerckhof** [comment]
Tracked here: meteor/meteor#7314

**Comment by stuhlmueller** [comment]
Thanks! Is the recommendation to wait until you've had a chance to use the Mac build machines to generate the missing binaries? (I'm asking since the referenced issue is closed already.)

Also, to clarify, will `meteor-scss` in fact still ship with binaries, even for Meteor 1.4? Based on [posts like this one](https://forums.meteor.com/t/coming-soon-meteor-1-4/23260) I assumed that this might not be the case: "we’re going to require Meteor users who rely on packages with binary dependencies to install a compiler toolchain on their development and build machines".

**Comment by sebakerckhof** [comment]
Sorry, I first linked to the wrong issue. I've edited the post.
Basically, you get a binary for node 0.10 which needs to be rebuild for node 4. Meteor should trigger this rebuild, but doesn't at this moment. You will indeed need a compiler chain, but I think Meteor also planned to include this, although I don't know if that's already the case.

**Comment by stuhlmueller** [comment]
That was helpful, thanks!
