### ISSUE TITLE
Error installing v3.2.0

### ISSUE THREAD

**Issue by inssitu** [fourseven/meteor-scss#197]
I have used v3.2.0 in all my apps to work with SASS, but now when I'm trying to install it I get this:

```
 => Errors while adding packages:             
                                              
While loading package fourseven:scss@3.2.0:
error: Command failed:
/Users/Tore/.meteor/packages/meteor-tool/.1.4.0-1.cbcnkw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm
rebuild --no-bin-links --update-binary
Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/darwin-x64-46_binding.node": HTTP error 404 Not Found
gyp: /Users/Tore/.node-gyp/4.4.7/common.gypi not found (cwd:
/Users/Tore/.meteor/packages/fourseven_scss/.3.2.0.2lwbi7++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1yofals/node_modules/node-sass)
while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit
(/Users/Tore/.meteor/packages/fourseven_scss/.3.2.0.2lwbi7++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1yofals/node_modules/node-sass/node_modules/pangyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command
"/Users/Tore/.meteor/packages/meteor-tool/.1.4.0-1.cbcnkw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/Tore/.meteor/packages/fourseven_scss/.3.2.0.2lwbi7++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1yofals/node_modules/node-sass/node_modules/pangyp/bin/node-gyp"
"rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd
/Users/Tore/.meteor/packages/fourseven_scss/.3.2.0.2lwbi7++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1yofals/node_modules/node-sass
gyp ERR! node -v v4.4.7
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok 
Build failed

npm ERR! Darwin 15.6.0
npm ERR! argv
"/Users/Tore/.meteor/packages/meteor-tool/.1.4.0-1.cbcnkw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/Tore/.meteor/packages/meteor-tool/.1.4.0-1.cbcnkw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/Tore/.meteor/packages/fourseven_scss/.3.2.0.2lwbi7++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1yofals/npm-debug.log
Cannot download "https://github.com/sass/node-sass/releases/download/v3.2.0/darwin-x64-46_binding.node": HTTP error 404 Not Found
gyp: /Users/Tore/.node-gyp/4.4.7/common.gypi not found (cwd:
/Users/Tore/.meteor/packages/fourseven_scss/.3.2.0.2lwbi7++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1yofals/node_modules/node-sass)
while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit
(/Users/Tore/.meteor/packages/fourseven_scss/.3.2.0.2lwbi7++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1yofals/node_modules/node-sass/node_modules/pangyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command
"/Users/Tore/.meteor/packages/meteor-tool/.1.4.0-1.cbcnkw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/Tore/.meteor/packages/fourseven_scss/.3.2.0.2lwbi7++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1yofals/node_modules/node-sass/node_modules/pangyp/bin/node-gyp"
"rebuild" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd
/Users/Tore/.meteor/packages/fourseven_scss/.3.2.0.2lwbi7++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1yofals/node_modules/node-sass
gyp ERR! node -v v4.4.7
gyp ERR! pangyp -v v2.2.1
gyp ERR! not ok 
Build failed

npm ERR! Darwin 15.6.0
npm ERR! argv
"/Users/Tore/.meteor/packages/meteor-tool/.1.4.0-1.cbcnkw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/node"
"/Users/Tore/.meteor/packages/meteor-tool/.1.4.0-1.cbcnkw++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/bin/npm"
"rebuild" "--no-bin-links" "--update-binary"
npm ERR! node v4.4.7
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! node-sass@3.2.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@3.2.0 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!
/Users/Tore/.meteor/packages/fourseven_scss/.3.2.0.2lwbi7++os.osx.x86_64+web.browser+web.cordova/plugin.compileScss.os.osx.x86_64/npm/node_modules/meteor/compileScss/compileScss/node_modules/.temp-1yofals/npm-debug.log
```

**Comment by sebakerckhof** [comment]
Please see the compatibility table in the readme
