### ISSUE TITLE
Scss files not compiling into the merged css file. 

### ISSUE THREAD

**Issue by 416serg** [fourseven/meteor-scss#212]
I have `application.scss`

```
@import "variables";
@import "../../node_modules/@sketchpixy/rubix/sass/rubix";
@import "../../node_modules/@sketchpixy/rubix/sass/vendor";
@import "colors";
@import "theme";
```

with `_colors.scss` being in the same folder, however the meteor merged-styles stylesheet isn't picking it up.

**Comment by sebakerckhof** [comment]
Please create a small reproduction.

**Comment by 416serg** [comment]
@sebakerckhof https://github.com/416serg/scss-test/invitations

**Comment by sebakerckhof** [comment]
When I try to run that, I get:
```
Unable to resolve some modules:

  "./dist/bundle/web/l20n-common.js" in /D/dev/scss-test/node_modules/l20n/package.json
(web.browser)

W20160823-16:38:04.247(2)? (STDERR) D:\dev\scss-test\.meteor\local\build\programs\server\shell-server.js:15
W20160823-16:38:04.249(2)? (STDERR) require("meteor-promise").makeCompatible(Promise, require("fibers"));
W20160823-16:38:04.251(2)? (STDERR)                           ^
W20160823-16:38:04.252(2)? (STDERR)
W20160823-16:38:04.253(2)? (STDERR) TypeError: require(...).makeCompatible is not a function
W20160823-16:38:04.255(2)? (STDERR)     at Object.<anonymous> (D:\dev\scss-test\.meteor\local\build\programs\server\shell-server.js:15:27)
W20160823-16:38:04.256(2)? (STDERR)     at Module._compile (module.js:409:26)
W20160823-16:38:04.258(2)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20160823-16:38:04.260(2)? (STDERR)     at Module.load (module.js:343:32)
W20160823-16:38:04.261(2)? (STDERR)     at Function.Module._load (module.js:300:12)
W20160823-16:38:04.263(2)? (STDERR)     at Module.require (module.js:353:17)
W20160823-16:38:04.264(2)? (STDERR)     at require (internal/module.js:12:17)
W20160823-16:38:04.266(2)? (STDERR)     at Object.<anonymous> (D:\dev\scss-test\.meteor\local\build\programs\server\boot.js:101:3)
W20160823-16:38:04.268(2)? (STDERR)     at Module._compile (module.js:409:26)
W20160823-16:38:04.269(2)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
```

**Comment by 416serg** [comment]
@sebakerckhof could you try cloning again? When I clone it and run `meteor npm install` -> `meteor npm start` it's working for me :/

**Comment by jmendiola222** [comment]
@416serg did u remember how you solve this? I have several .scss files in the project but none seems to be bundled.

> Without any additional configuration after installation, this package automatically finds all .scss and .sass files in your project, compiles them with node-sass, and includes the resulting CSS in the application bundle that Meteor sends to the client. The files can be anywhere in your project.
