### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by Oneia** [fourseven/meteor-scss#221]
Cant add to project,  i have error at randomNumber% 
C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\isopackets\ddp\npm\node_modules\meteor\promise\node_modules\meteor-promise\promise_server.js:165
      throw error;
      ^

Error: unexpected eof
    at decorate (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:67:36)
    at Extract.Abstract.error (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\abstract.js:61:12)
    at Extract._streamEnd (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\extract.js:91:35)
    at BlockStream.<anonymous> (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:51:8)
    at emitNone (events.js:67:13)
    at BlockStream.emit (events.js:166:7)
    at BlockStream._emitChunk (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:203:10)
    at BlockStream.resume (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\block-stream\block-stream.js:58:15)
    at Extract.Reader.resume (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\reader.js:242:34)
    at Entry.<anonymous> (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\parse.js:261:8)
    at emitNone (events.js:67:13)
    at Entry.emit (events.js:166:7)
    at Entry.resume (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\tar\lib\entry.js:93:8)
    at resume (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:62:16)
    at unblockEntry (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:43:28)
    at Entry.<anonymous> (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\collect.js:47:9)
    at FileWriter.<anonymous> (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\dir-writer.js:146:11)
    at emitNone (events.js:67:13)
    at FileWriter.emit (events.js:166:7)
    at WriteStream.<anonymous> (C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\fstream\lib\file-writer.js:45:10)
    at emitOne (events.js:77:13)
    at WriteStream.emit (events.js:169:7)
    at C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:205:14
    at C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\graceful-fs\graceful-fs.js:232:16
    at C:\Users\User\AppData\Local\.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\cordova-lib\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:232:16
    at FSReqWrap.oncomplete (fs.js:82:15)

**Comment by NightFury20** [comment]
I'm having the same problem

**Comment by jamesabels** [comment]
Same here on OSX 10.11.6 but it seems to be an issue with the NPM package.

**Comment by aaroncalderon** [comment]
similar issue. see https://github.com/meteor/meteor/issues/7703

**Comment by sebakerckhof** [comment]
Closing since not related to this package.
