### ISSUE TITLE
Problem running tests on react components that import scss file

### ISSUE THREAD

**Issue by etenoch** [fourseven/meteor-scss#242]
Not sure if this is the right place to ask.

My tests are failing when run using practicalmeteor:mocha and spacejam due to my scss not being imported properly. 

Top of my React component
```
import './TestComponent.scss'
```

Error when running tests.
```
Error: Cannot find module './TestComponent.scss'
    at require (packages/modules-runtime.js:109:19)
    at meteorInstall.imports.ui.components.TestComponent.jsx (imports/ui/components/TestComponent.jsx:11:1)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at Module.require (packages/modules-runtime.js:106:16)
    at Module.Mp.import (/Users/enoch/.meteor/packages/modules/.0.7.7.15s1dhd++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:70:16)
    at meteorInstall.imports.ui.components.tests.js (imports/ui/components.tests.js:1:1)
    at fileEvaluate (packages/modules-runtime.js:181:9)
    at require (packages/modules-runtime.js:106:16)
    at /private/var/folders/q9/jxygk5nd0rjcjl8skmfn9g3c0000gn/T/meteor-test-run15abg97/.meteor/local/build/programs/server/app/app.js:3156:1
    at /private/var/folders/q9/jxygk5nd0rjcjl8skmfn9g3c0000gn/T/meteor-test-run15abg97/.meteor/local/build/programs/server/boot.js:295:34
```

App runs fine in browser using correct css.
Tests run fine when using the web browser to run the client side tests (not using spacejam).
Tests also run fine when ```import './TestComponent.scss'``` is commented out.

**Comment by sebakerckhof** [comment]
This error does not origin from this package. Module not found errors would be either user error or a meteor bug.

**Comment by Floriferous** [comment]
@etenoch Did you find a solution for this issue?

**Comment by sebakerckhof** [comment]
For future reference: https://github.com/meteor/meteor/issues/9562#issuecomment-359412178
