### ISSUE TITLE
Crash when using lighten() function

### ISSUE THREAD

**Issue by yorrd** [fourseven/meteor-scss#286]
When I use the `lighten()` method in any `scss` file, Meteor crashes with the error found below.

`meteor` version: 1.8.1-beta.13

`fourseven:scss` version: 4.10

Please let me know if I can help you debug this further.

```
/home/yorrd/.meteor/packages/static-html/.1.2.2.1iiezyg.nj5k++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:190
      throw error;
      ^
undefined
 => awaited here:
    at Promise.await (/home/yorrd/.meteor/packages/static-html/.1.2.2.1iiezyg.nj5k++os+web.browser+web.cordova/plugin.compileStaticHtmlBatch.os/npm/node_modules/meteor/promise/node_modules/meteor-promise/promise_server.js:39:12)
    at JsOutputResource.finalize (/tools/isobuild/compiler-plugin.js:897:7)
    at JsOutputResource.hasPendingErrors (/tools/isobuild/compiler-plugin.js:924:10)
    at JsOutputResource.reportPendingErrors (/tools/isobuild/compiler-plugin.js:929:14)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:849:14)
    at each (/tools/isobuild/import-scanner.js:907:14)
    at _.each._.forEach (/home/yorrd/.meteor/packages/meteor-tool/.1.8.1-beta.13.11369o3.fchv++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:871:5)
    at each (/tools/isobuild/import-scanner.js:907:14)
    at _.each._.forEach (/home/yorrd/.meteor/packages/meteor-tool/.1.8.1-beta.13.11369o3.fchv++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:871:5)
    at each (/tools/isobuild/import-scanner.js:907:14)
    at _.each._.forEach (/home/yorrd/.meteor/packages/meteor-tool/.1.8.1-beta.13.11369o3.fchv++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:871:5)
    at each (/tools/isobuild/import-scanner.js:907:14)
    at _.each._.forEach (/home/yorrd/.meteor/packages/meteor-tool/.1.8.1-beta.13.11369o3.fchv++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/underscore/underscore.js:87:22)
    at ImportScanner._scanFile (/tools/isobuild/import-scanner.js:871:5)
    at outputFiles.forEach.file (/tools/isobuild/import-scanner.js:529:14)
    at Array.forEach (<anonymous>)
    at ImportScanner.scanImports (/tools/isobuild/import-scanner.js:527:22)
    at sourceBatches.forEach.batch (/tools/isobuild/compiler-plugin.js:1301:17)
    at Array.forEach (<anonymous>)
    at Function.computeJsOutputFilesMap (/tools/isobuild/compiler-plugin.js:1269:19)
    at ClientTarget._emitResources (/tools/isobuild/bundler.js:1121:8)
    at buildmessage.enterJob (/tools/isobuild/bundler.js:847:12)
    at Object.enterJob (/tools/utils/buildmessage.js:388:12)
    at ClientTarget.make (/tools/isobuild/bundler.js:835:18)
    at /tools/isobuild/bundler.js:3143:14
    at webArchs.forEach.arch (/tools/isobuild/bundler.js:3294:25)
    at Array.forEach (<anonymous>)
    at /tools/isobuild/bundler.js:3248:14
    at Object.capture (/tools/utils/buildmessage.js:283:5)
    at bundle (/tools/isobuild/bundler.js:3124:31)
    at files.withCache (/tools/isobuild/bundler.js:3069:32)
    at Object.withCache (/tools/fs/files.js:1712:12)
    at Object.bundle (/tools/isobuild/bundler.js:3069:16)
    at Profile.run (/tools/runners/run-app.js:569:24)
    at Function.run (/tools/tool-env/profile.js:490:12)
    at bundleApp (/tools/runners/run-app.js:568:34)
    at AppRunner._runOnce (/tools/runners/run-app.js:610:35)
    at AppRunner._fiber (/tools/runners/run-app.js:908:28)
    at /tools/runners/run-app.js:398:12
```

**Comment by met5678** [comment]
I'm seeing this error frequently lately, wonder if a meteor upgrade broke something?

**Comment by sebakerckhof** [comment]
I can't seem to reproduce this.

I get something like:
```
While processing files with fourseven:scss (for target web.browser):
   /client/test.scss: Scss compiler error: Error: Undefined variable:
   "$color".
   on line 3 of {}/imports/_import.scss
   from line 1 of {}/client/test.scss
   >>   background-color: lighten($color, 2)
```

Can you make a small reproduction?

**Comment by nathanschwarz** [comment]
Hi there,

I have the same errors all the time.
I think it's because we're using the meteor `static-html` package, and we're importing the scss file in our Js files as so:

`import 'path/.../.../file.scss'`

Meteor seems to crash because it can't import the css file in JS (  it doesn't exists yet because of a failed scss compilation).

It's really hard to debug because we can't see where the error is in our scss.

I wonder if you can do something about it...
